GEMINI_API_KEY = "AIzaSyAIac9gDIl0mS2jzgG0IrAfSGQahh4iURg"

[postgres]
dialects ="postgresql"
host="aws-1-sa-east-1.pooler.supabase.com"
port="6543"
database="postgres"
user="postgres.pewhhbmuotrxrclslknz"
password="Ku48Fu49Yu75K@78"
