GEMINI_API_KEY=AQ.Ab8RN6ILxCA1FGe9_XAewTpc1IpMTGvsxb3foyS4OiYKEyAEwg

[postgres]
dialects ="postgresql"
host="aws-1-sa-east-1.pooler.supabase.com"
port="6543"
database="postgres"
user="postgres.pewhhbmuotrxrclslknz"
password="Ku48Fu49Yu75K@78"
