GEMINI_API_KEY=AIzaSyC4v_VsZeEMbtIzVgiB_zWk3cGyF_h14WU

[postgres]
dialects ="postgresql"
host="aws-1-sa-east-1.pooler.supabase.com"
port="6543"
database="postgres"
user="postgres.pewhhbmuotrxrclslknz"
password="Ku48Fu49Yu75K@78"
